### PR TITLE
Update to Epi 11 and some improvements

### PR DESCRIPTION
**Pull request by jstemerdink**

### CODE REVIEW

**Comment by LinusEkstrom** [comment]
Hi @jstemerdink,

Just want to acnolage that I've seen this but been on vacation, so I've not had time to review it yet. Hoping to do so during this week.

**Comment by jstemerdink** [comment]
@LinusEkstrom No worries, hope you had a great vacation! See you at the summit In October?

**Comment by LinusEkstrom** [comment]
I will most likely not travel to the US this autumn for the EMVP summit and Ascend event, but I'll surely join Sthm Ascend and potentially some of the other European Ascend events. Hoping for the next EMVP event a bit closer...

**Comment by LinusEkstrom** [comment]
Nice additions to the code and usage samples, good work! Will be looking to see if this is something we'll start using for Epinova.

**Comment by jstemerdink** [comment]
You did the groundwork :) Used it a few projects myself

**Comment by LinusEkstrom** [comment]
Good to hear, and I remember you telling me this before when we met. I've been spending quite a lot of effort in taking the "Feature Folders" concept further then what I've seen others do, with the goal to have as little as possible of feature specific code outside of the feature folder. Settings has been a nail in the eye, that's somewhat mitigated by using this system.

**Pull request merged**
